export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'

export const MOVIE_SELECTED = 'MOVIE_SELECTED'